# Generated by Django 5.1.7 on 2025-03-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_attendance', models.PositiveIntegerField(default=75, help_text='Minimum attendance percentage required to pass')),
                ('late_policy', models.PositiveIntegerField(default=3, help_text='Number of late arrivals that count as one absence')),
                ('notification_threshold', models.PositiveIntegerField(default=70, help_text='Send warning when attendance falls below this percentage')),
                ('grace_period', models.PositiveIntegerField(default=15, help_text='Allowed minutes after scheduled time before marked late')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Rule',
                'verbose_name_plural': 'Attendance Rules',
            },
        ),
    ]
