# Generated by Django 5.1.7 on 2025-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerule',
            name='grace_period',
            field=models.PositiveIntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='late_policy',
            field=models.PositiveIntegerField(default=3, help_text='Number of late arrivals = 1 absence'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='minimum_attendance',
            field=models.PositiveIntegerField(default=75, help_text='Minimum attendance percentage required'),
        ),
        migrations.AlterField(
            model_name='attendancerule',
            name='notification_threshold',
            field=models.PositiveIntegerField(default=70, help_text='Warning threshold percentage'),
        ),
    ]
