# Generated by Django 5.1.7 on 2025-04-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_course_credit_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
    ]
