# Generated by Django 5.1.7 on 2025-04-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_description_remove_course_is_active'),
        ('departments', '0002_alter_department_options_alter_department_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='departments.department'),
        ),
    ]
