# Generated by Django 5.1.7 on 2025-04-21 06:07

import django.db.models.deletion
import facial_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_data', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facialdata',
            options={'verbose_name_plural': 'Facial Data'},
        ),
        migrations.RemoveField(
            model_name='facialdata',
            name='facial_features',
        ),
        migrations.RemoveField(
            model_name='facialdata',
            name='user',
        ),
        migrations.AddField(
            model_name='facialdata',
            name='analysis_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='facialdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facialdata',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facial_data', to='students.student'),
        ),
        migrations.AddField(
            model_name='facialdata',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=facial_data.models.liveness_video_path),
        ),
    ]
